### ISSUE TITLE
Need explanation of coverage block

### ISSUE THREAD

**Issue by riuandg5** [stepin654321/MiniProject_Template#99]
https://github.com/stepin654321/MiniProject_Template/blob/31d1ade852e036a6b6076433ca7810764f268bcb/Example_Programs/programming_concpets/calculator_complex/Makefile#L40-L43

Please explain the script of the coverage block.

Doubts:

- Why `main.c` is not included in line 41?
- If `main.c` is not included then using `/src` and `/inc` files that do not include any `main()` function, how it will generate the executable file?

I think we have to include `main.c` in line 41 or using header files we can only generate object files that have to be linked with `main.c` to finally generate an executable file.

**Comment by Bharathgopal** [comment]
**main.c** is a business logic file where the user input and output will be added.
The focus here is to test and verify the **functions** that are written and for that **test_complex_calculator.c** has **main()** function.

**Comment by Bharathgopal** [comment]
Please close the issue if its answered.

**Comment by riuandg5** [comment]
> In the command **gcc -fprofile-arcs -ftest-coverage $(SRC) $(INC) -o $(call FixPath,$(BUILD_DIR)/$(TEST_PROJ_NAME).$(EXEC))**
> 
> gcc - Compiler
> fprofile-arcs & -ftest-coverage - Compiler flags to info about coverage and profiling when the application runs and create files that can be analysed by gcov
> 
> The second line **$(call FixPath,$(BUILD_DIR)/$(TEST_PROJ_NAME).$(EXEC))** runs the executable file.
> The third line, creates the coverage files .gcda & .gcov files.
> 
> **main.c** is a business logic file where the user input and output will be added.
> The focus here is to test and verify the **functions** that are written and for that **test_complex_calculator.c** has **main()** function.
> Also, the coverage is always done for unit testing and not the actual application.

Thank you! I understood that we have to check coverage for testing and not the main app.
